apiVersion: v1
kind: Service
metadata:
  name: graphana-service
  namespace: monitoring                                                                                
  annotations:                                                                                         
    graphana.io/scrape: 'true'                                                                     
    graphana.io/path:   /                                                                          
    graphana.io/port:   '8081' 
spec:
  selector: 
    app: graphana-server
  type: NodePort
  ports:
    - port: 8081
      targetPort: 3000
      nodePort: 30001
